language: ruby
services: postgresql
script: "bundle exec rspec spec"
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
notifications:
  email: false
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database mori_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
cache:
  bundler: true
