language: ruby
services: postgresql
script: "bundle exec rspec spec"
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
notifications:
  email: false
before_script:
  - psql -c 'create database myapp_test;' -U postgres
cache:
  bundler: true
