language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
notifications:
  email: false
script:
  - RAILS_ENV=test bundle exec rake app:db:test:prepare --trace
  - bundle exec rspec spec
cache:
  bundler: true
