language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
notifications:
  email: false
before_script:
  - cp config/database.travis.yml spec/dummy/config/database.yml
  - mv config/secret.travis.yml config/initializers/secret_token.rb
script:
  - bundle exec rake app:db:migrate
  - RAILS_ENV=test bundle exec rake app:db:test:prepare --trace
  - bundle exec rspec spec
cache:
  bundler: true
