language: ruby
services: postgresql
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - DB=postgresql
gemfile:
  - Gemfile
notifications:
  email: false
before_script:
  - cp config/database.travis.yml spec/dummy/config/database.yml
  - psql -c 'create database mori_test' -U postgres
  - psql -c 'create database mori_users' -U postgres
script:
  - RAILS_ENV=test bundle exec rake app db:migrate --trace
  - RAILS_ENV=user bundle exec rake db:migrate --trace
  - bundle exec rspec spec
cache:
  bundler: true
