development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development
  pool: 5
  username: AaronMiler

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: dummy_production
  pool: 5
  username: dummy
  password:
